// The hitbox diagram: a card's firing pattern drawn as cells, not described.
//
// "3x3 at exactly range 4" takes a re-read and still leaves you counting; the
// diagram shows the gap in front of the blast at a glance. Every shape here is
// generated by geomCells() — the same function the combat board highlights
// from — so a diagram can never disagree with what the weapon actually does.
//
// Two patterns need a distinction the cells alone cannot carry. `first` and
// `furthest` search the whole lane but strike one body out of it, so the reach
// is drawn faint and the cell they settle on is drawn solid. Everything else
// covers exactly what it lights.

import {LANES, COLS} from '../state/constants.js';
import {POOL} from '../content/cards.js';
import {BEST} from '../content/hostiles.js';
import {geomCells} from '../rules/targeting.js';
import {gearOf} from '../save/progression.js';

// A window wide enough for the deepest pattern (blast4 reaches +5) plus one
// cell behind, and tall enough for the three lanes anything spans.
const HB_COLS = 7;
const HB_LANES = 3;
const HB_ORIGIN = {lane: 1, col: 1};
// Hostiles advance toward column 0, so their diagram reads right to left.
const HB_FOE_ORIGIN = {lane: 1, col: 5};

/** Patterns that hunt a target rather than covering fixed ground. */
const HB_SEEKS = {first: 'nearest', furthest: 'deepest', lane: null, boardFurthest: 'deepest'};

/**
 * A card's pattern as cell offsets, built from the rules layer rather than
 * restated here. Uses a board-sized origin so nothing clips at an edge, then
 * re-bases onto the diagram window.
 */
function hbOffsets(id) {
  const k = POOL[id];
  const g = gearOf(id);
  // Every card diagrams its own printed pattern now — a Frame draws its base
  // weapon, and each gear CARD carries the diagram of what it mounts.
  // A fitted weapon gear draws ITS pattern — that is the gun this card fires now.
  const tg = (g && g.tg) || k.tg;
  const dmg = g && g.tg ? g.dmg : k.dmg;
  if (!tg || tg === 'none' || !dmg) return null;

  // A stand-in with just the fields geomCells reads. Deliberately not mkUnit:
  // the diagram is the card's printed pattern, not one unit's live situation.
  const stub = {
    tg,
    dmg,
    single: g && g.tg ? !!g.single : !!k.single,
    size: k.size || 1,
    indirect: !!k.indirect || !!(g && g.indirect),
    rearsight: !!(g && g.rearsight),
    uid: -1,
  };
  const mid = {lane: Math.floor(LANES / 2), col: 2};
  return geomCells(stub, mid).map(i => [Math.floor(i / COLS) - mid.lane, (i % COLS) - mid.col]);
}

/**
 * One diagram.
 *
 * `origin` moves the actor within the window — yours sits near the left with
 * the board ahead of it, a hostile sits near the right, because that is the
 * direction each of them faces. `hit`/`reach` name the fill classes so the
 * hostile diagram reads magenta where a card's reads gold.
 */
function hbGrid(cells, opts = {}) {
  const {
    solid = null, self = 'me', cls = '',
    origin = HB_ORIGIN, hit = 'hbhit', reach = 'hbreach',
  } = opts;
  const {infl = null} = opts;
  const key = (l, c) => l + ',' + c;
  const mark = list => new Set(list.map(([l, c]) => key(l + origin.lane, c + origin.col)));
  const lit = mark(cells);
  const hot = solid ? mark(solid) : null;
  const aura = infl ? mark(infl) : null;

  let h = '';
  for (let l = 0; l < HB_LANES; l++) {
    for (let c = 0; c < HB_COLS; c++) {
      const at = key(l, c);
      let cn = '';
      if (l === origin.lane && c === origin.col) cn = self;
      else if (hot && hot.has(at)) cn = hit;
      else if (lit.has(at)) cn = hot ? reach : hit;
      else if (aura && aura.has(at)) cn = 'hbinfl';
      h += `<i class="${cn}"></i>`;
    }
  }
  return `<div class="hb${cls ? ' ' + cls : ''}" aria-hidden="true">${h}</div>`;
}

/**
 * The range block for a card's focus view, or '' when it has no weapon.
 * @param {string} id card id
 */
export function hitboxFor(id) {
  const offs = hbOffsets(id);
  if (!offs || !offs.length) return '';
  const k = POOL[id];
  const tg = k.tg;
  const seek = HB_SEEKS[tg];

  // A seeking pattern settles on one cell out of its reach: draw that one
  // solid so "searches here, strikes there" reads without a caption.
  let solid = null;
  if (seek) {
    const inLane = offs.filter(([l]) => l === 0);
    const pick = seek === 'nearest'
      ? inLane.reduce((a, b) => (a && a[1] <= b[1] ? a : b), null)
      : inLane.reduce((a, b) => (a && a[1] >= b[1] ? a : b), null);
    if (pick) solid = [pick];
  }

  const label = tg === 'boardFurthest' ? 'Any lane'
    : seek ? (seek === 'nearest' ? 'Nearest in lane' : 'Deepest in lane')
      : `${offs.length} tile${offs.length > 1 ? 's' : ''}`;

  return `<div class="frange">${hbGrid(offs, {solid})}
    <div class="rl"><b>Reach</b><span>${label}</span></div></div>`;
}

/**
 * The same block for a hostile. They carry no `tg` at all — their threat is
 * where they strike, how fast they close, and what their presence does to the
 * lane — so this reads right to left, the way they come.
 */
export function hitboxForFoe(kid) {
  const D = BEST[kid];
  const ranged = D.hold !== undefined;
  const cells = [];   // threatened ground
  const solid = [];   // struck this turn
  const infl = [];    // a standing effect, not an attack

  if (D.dmg) {
    if (ranged) {
      // Halts at a column and fires the length of the lane behind it.
      for (let c = 1; c <= HB_FOE_ORIGIN.col; c++) cells.push([0, -c]);
      solid.push([0, -1]);
    } else {
      solid.push([0, -1]);
      const steps = Math.max(1, Math.floor(D.spd || 0));
      for (let d = 1; d <= steps; d++) cells.push([0, -d]);
    }
  }

  const left = -HB_FOE_ORIGIN.col;
  const right = HB_COLS - 1 - HB_FOE_ORIGIN.col;
  // The Chorus buffs every hostile alive, so its reach is the board, not a
  // lane — the one hostile whose effect the lane treatment would understate.
  // A boss threatens the engagement, not a lane: breaches anywhere on the
  // board, every emitter at once, reflection up whichever barrel fires.
  if (D.aura || D.boss) {
    for (let l = -1; l <= 1; l++) for (let c = left; c <= right; c++) if (l || c) infl.push([l, c]);
  } else if (D.lanefloor || D.jam || D.mend || D.mindctrl || D.spawn) {
    for (let c = left; c <= right; c++) if (c !== 0) infl.push([0, c]);
  }

  if (!cells.length && !solid.length && !infl.length) return '';
  const label = D.boss ? 'The whole engagement'
    : D.aura ? 'Every hostile alive'
      : ranged ? 'Whole lane, from cover'
      : D.dmg ? (D.spd >= 2 ? 'Ahead, two cells a turn' : 'The cell ahead')
        : 'Its whole lane';

  return `<div class="frange">${hbGrid(cells, {
    solid: solid.length ? solid : null,
    infl: infl.length ? infl : null,
    self: 'hbfoe', origin: HB_FOE_ORIGIN, hit: 'hbstrike', reach: 'hbthreat',
  })}
    <div class="rl"><b style="color:#ff8fb5">Reach</b><span>${label}</span></div></div>`;
}
