// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// The 3 operation bosses and their encounter scripts.

export const BOSSDEF = {
  gantry: {
    op: "ironveil",
    hp: 40,
    shield: 30,
    w: 3,
    h: 2,
    l: 1,
    c: 5,
    turns: 18,
    add: "fabricant",
    ramp: [1, 2, 3],
    cellDmg: 2,
    p1: "Shielded — fabricating, not firing",
    p2: "Shield down — every emitter firing, assembly continuing",
    bt: "SHIELD COLLAPSE",
    bb: "The containment field fails and the rig is suddenly aware of you. Every emitter it has comes online at once.",
    brief: {
      freq: "141.83",
      net: "残心ネット",
      cap: "Kill Order · Priority target briefing",
      from: {n: "Hikaru", r: "CC Liaison"},
      beats: [
        {
          say: ["Commander. According to the data your team is sending, the yards' central fabricator system is live again. But the data we're seeing is all sorts of wrong.", "Whatever you are facing has taken control of the line. We are designating it: THE GANTRY."],
          reply: "Understood. So these... creatures we're engaging are produced from it?",
        },
        {
          say: ["Affirmative. It looks to be absorbing our tech and producing soldiers via conveyor belts.", "The system has a shield in place, and it will need to be taken offline before your team has any chance at the GANTRY itself. Note that once that shield comes down, its auto-defense systems will activate."],
          reply: "So its shield is protecting us.",
        },
        {
          say: ["Until you choose otherwise, yes. Thin the enemy forces, take down the shield, then destroy the fabrication machine. How you approach the battle is at your discretion.", "One more thing. We've received updates that after eighteen cycles of combat, the GANTRY will become fully operational and begin fabrication of their forces in full. If that happens, we lose far more than those shipyards."],
          reply: "Understood. Out.",
        },
      ],
      close: "Channel closed. Target designate: THE GANTRY. The clock starts on your descent.",
    },
    debrief: {
      freq: "141.83",
      net: "残心ネット",
      cap: "After-action · CC uplink",
      from: {n: "Hikaru", r: "CC Liaison"},
      beats: [
        {
          say: ["Good work down there, Commander. While you fought, the picture got wider. According to reports, hostile creatures are engaging UPE forces across the system.", "They seem bio-organic at first glance — but they absorb and recreate their own versions of our tech at alarming speeds. What you destroyed today was one of them learning to build."],
          reply: "So the yards were a factory for them. How far does this go?",
        },
        {
          say: ["We don't know yet. What we do know is that this can no longer be called an isolated incident.", "As of this transmission, Zanshin Protocol has been activated across the system. Every commander. Every line. No wasted motion."],
          reply: "Acknowledged. Zanshin. Out.",
        },
      ],
      close: "Channel closed. ZANSHIN PROTOCOL — active system-wide.",
    },
  },
  brood: {
    op: "blackmarrow",
    hp: 34,
    w: 2,
    h: 2,
    l: 1,
    c: 5,
    turns: 18,
    seamEvery: 3,
    breachDmg: 4,
    breachPool: ["crawler", "hulk", "spitter", "breacher"],
    tendrilDmg: 2,
    splitBodies: 3,
    p1: "Excavating — breaches and tendrils",
    p2: "Split — three bodies working separate faces",
    bt: "NEW FACES OPENED",
    bb: "Standard procedure for a collapsed shaft. The body contracts and the work continues elsewhere.",
    brief: {
      freq: "141.86",
      net: "残心ネット",
      cap: "Kill Order · Priority target briefing",
      from: {n: "Hikaru", r: "CC Liaison"},
      beats: [
        {
          say: ["Commander. Our previous forward teams reported engagement with a target designated: THE BROOD MOTHER.", "According to the limited data we were able to procure, it is digging for crystals to feed and multiply. It lays its brood into the ground — they burrow, and they attack from underneath."],
          reply: "Sitrep on those teams, and any updates to our HUD systems?",
        },
        {
          say: ["Teams are assumed lost. Breach points are marked anywhere on the field — your half included — one full turn before something claws out of them. Your HUD will keep you updated. Any soldier standing on an incoming breach has been instructed to take the hit and seal it. Nothing surfaces. One for the many.", "The tendrils are another matter. One lash a turn, an entire row at once, and no warning. Plan around the breaches; budget hull for the tendrils."],
          reply: "Hm. Understood. Anything else?",
        },
        {
          say: ["Our scientists believe that at half strength, it will split. Three bodies, separate lanes — and every one of them must die, or the tunnels stay live.", "Watch your footing, Commander."],
          reply: "Understood. Out.",
        },
      ],
      close: "Channel closed. Target designate: THE BROOD MOTHER. The tunnels are waiting.",
    },
    debrief: {
      freq: "141.86",
      net: "残心ネット",
      cap: "After-action · CC uplink",
      from: {n: "Hikaru", r: "CC Liaison"},
      beats: [
        {
          say: ["The tunnels are quiet, Commander. For the first time in months, the seismic net reads nothing at all.", "Analysis of the remains confirms what Central has feared. It was digging for the source of the crystal, it seems. Specifically, crystal-fused ore. Nesting, feeding, multiplying — and eating anything along the way."],
          reply: "Then they feed on the same crystal we use for our weapons and frames?",
        },
        {
          say: ["Unfortunately, yes. These creatures feed on crystal and anything that has it — then eat it, and transfer the knowledge across their species to produce more of themselves in various forms.", "Scouts have even reported they have started implementing Frame technology into their ranks.", "Further details will be shared as we get them. Zanshin Protocol remains in effect. Stay safe, Commander."],
          reply: "Copy. Out.",
        },
      ],
      close: "Channel closed. Sub-crust contacts: zero. For now.",
    },
  },
  prism: {
    op: "sunderglass",
    hp: 70,
    w: 2,
    h: 3,
    l: 1,
    c: 5,
    turns: 18,
    reflect: 0.25,
    fragments: 4,
    growCap: 1.25,
    p1: "Inert — reflecting damage taken",
    p2: "Fractured — four fragments, each growing",
    bt: "FRACTURE",
    bb: "Crystal under sustained stress fails along its planes. You have made three more problems by solving one badly.",
    brief: {
      freq: "141.89",
      net: "残心ネット",
      cap: "Kill Order · Priority target briefing",
      from: {n: "Hikaru", r: "CC Liaison"},
      beats: [
        {
          say: ["Commander, this one is unlike anything on the registry. Seventy points of crystal standing in the glass fields, and in six weeks of observation it has attacked nothing. Well. Technically.", "We're designating this one THE PRISM."],
          reply: "Explain.",
        },
        {
          say: ["A quarter of everything you put into it comes straight back. Big hits reflect big. Small shots send small. We think spreading the damage, and rotating the wounded out, is your best bet."],
          reply: "Has anyone broken through yet?",
        },
        {
          say: ["Remember that technicality? We had a Proto Frame connected to power batteries and hit it with a full blast. We lost the whole contingent of UPE forces as a result.", "But it gave us results. It shatters. Four fragments, separate lanes, each still reflecting — and each growing back every turn. There is a ceiling to the growth, but a slow gun will not beat it there. When it breaks, Central believes killing the pieces fast and all at once will do it.", "Watch the reflection, Commander. For once, your face isn't the most dangerous thing here."],
          reply: "Funny. Almost. Signing out.",
        },
      ],
      close: "Channel closed. Target designate: THE PRISM. Mind your own fire.",
    },
    debrief: {
      freq: "141.89",
      net: "残心ネット",
      cap: "After-action · CC uplink",
      from: {n: "Hikaru", r: "CC Liaison"},
      beats: [
        {
          say: ["Confirmed shattered, Commander — all four fragments dark. And now that it is, I will tell you what analysis would not put on an open channel.", "It was never inert. Every hit it reflected, it measured. Weapons, output, timing — the glass fields were an instrument, and we were the reading."],
          reply: "It was studying our fire.",
        },
        {
          say: ["Studying us. Whatever these things answer to now holds six weeks of data on how the UPE fights — and you have just shown it the one way to lose to us: patience, spread fire, no wasted motion.", "Zanshin Protocol stands. What comes next will have read the manual, Commander. Make sure it still loses."],
          reply: "Understood. Out.",
        },
      ],
      close: "Channel closed. The glass fields are dark. The system is watching back.",
    },
  },
};
