// GENERATED by tools/gen-art.py from art/sources/.
// Drop an image named <cardId>.png/jpg there and run `npm run gen:art` —
// do not edit this file by hand. Cards without an entry fall back to
// their procedural sigil.

export const CARD_ART = {
};
