// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// Enemy doctrines: how a wave distributes itself across lanes.

export const DOCTRINE = [
  {k: "focus", w: 26, n: "Concentrated push"},
  {k: "spread", w: 38, n: "Broad assault"},
  {k: "probe", w: 36, n: "Probing attack"},
];
