// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// The 8 gear pieces, one slot per card, bought with salvage.

export const GEAR = {
  barrel: {n: "Extended Barrel", cost: 45, d: "+1 damage to this unit.", dmg: 1},
  plating: {n: "Reactive Plating", cost: 40, d: "+3 hull.", hp: 3},
  servo: {n: "Servo Legs", cost: 80, d: "May move AND fire in the same turn.", servo: 1},
  uplink: {n: "Targeting Uplink", cost: 60, d: "Ignores hostile armour floors.", pen: 1},
  kit: {n: "Field Kit", cost: 75, d: "Costs 1 less deploy point, minimum 1.", dp: -1},
  coolant: {
    n: "Coolant Core",
    cost: 90,
    d: "Ability cooldowns are 1 turn shorter, minimum 1.",
    cool: 1,
  },
  phase: {
    n: "Phase Cloak",
    cost: 105,
    d: "The first killing blow leaves it at 1 hull instead. Once per deployment.",
    phase: 1,
  },
  weave: {
    n: "Ablative Weave",
    cost: 70,
    d: "+1 shield capacity. Stacks with regenerating shields.",
    shield: 1,
  },
  dropod: {
    n: "Drop Pod",
    cost: 110,
    d: "May deploy straight onto a hostile below Specialist tier, crushing it on landing and holding the cell.",
    crush: 1,
  },
  stim: {
    n: "Stim Injector",
    cost: 70,
    d: "+2 damage. The unit loses 1 hull every turn it lives.",
    dmg: 2,
    decay: 1,
  },
  ifield: {
    n: "I-Field",
    cost: 90,
    d: "Immune to indirect fire — Mortar, Plasma Artillerist, anything that arcs.",
    immuneIndirect: 1,
  },
};
