// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// The team leads and their perks.

export const LEADS = {
  ironbrand: {
    n: "VALE",
    call: "IRONBRAND",
    role: "Line Commander",
    col: "#4de8ff",
    bio: "Held the Sundering Gate for nine days with a company of forty. Believes armour is a philosophy.",
    passive: {n: "Hardened Frames", d: "Every unit you deploy arrives with +1 hull."},
  },
  wildfire: {
    n: "KESTREL",
    call: "WILDFIRE",
    role: "Strike Officer",
    col: "#ff4d8f",
    bio: "Three commendations, two demotions, one very expensive orbital incident. Fights fast and asks after.",
    stratagem: "requisition",
  },
  coldwire: {
    n: "SABLE",
    call: "COLDWIRE",
    role: "Field Engineer",
    col: "#ffc94d",
    bio: "Speaks to machines more than people. The machines, notably, keep working.",
    passive: {n: "Nanite Weave", d: "All your units repair 1 hull at the end of every turn."},
  },
  loneedge: {
    n: "GRAHAM",
    call: "LONE EDGE",
    role: "Frontline Duelist",
    col: "#4de8ff",
    bio: "Treats every engagement as a private duel. Plunges into the centre of a formation and trusts the squad to keep up or stay clear.",
    passive: {n: "Lone Edge", d: "A unit with no friendly in an adjacent cell deals +2 damage."},
    stratagem: "duel",
  },
  skunkworks: {
    n: "KUDELIA",
    call: "SKUNKWORKS",
    role: "Field Engineer",
    col: "#5dffa0",
    bio: "Ex-skunkworks, permanently caffeinated, trusts machines over orders. Treats the battlefield as a laboratory with inconvenient variables.",
    passive: {
      n: "Field Fabrication",
      d: "Tech units deploy with +2 hull and repair 1 hull every turn.",
    },
    stratagem: "refit",
  },
  quietstep: {
    n: "ALLENBY",
    call: "QUIETSTEP",
    role: "Infiltrator",
    col: "#9d6bff",
    bio: "Soft-spoken until the unit initialises. Moves through a turn like a rumour and neutralises threats before they resolve.",
    passive: {
      n: "Quietstep",
      d: "Cards that deploy on hostile ground cost 1 less deploy point, minimum 1.",
    },
    stratagem: "insertion",
  },
  firebrand: {
    n: "CAGALLI",
    call: "FIREBRAND",
    role: "Saboteur",
    col: "#ff4d8f",
    bio: "Walked away from a military pedigree to fight at the line. Argues with command, never with her squad.",
    passive: {n: "Firebrand", d: "+2 deploy points on any turn after you lost a unit."},
    stratagem: "breach",
  },
  riptide: {
    n: "YAZAN",
    call: "RIPTIDE",
    role: "Skirmisher",
    col: "#e07a35",
    bio: "Treats a firefight like a contact sport. No patience for planning, uncanny instinct for where the line is about to break.",
    passive: {n: "Riptide", d: "Units that repositioned this turn take 1 less damage."},
    stratagem: "grapple",
  },
};
