// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// What each unlockable team lead is gated behind.

export const LEADGATES = {
  loneedge: {req: "rank", value: 2},
  skunkworks: {req: "rank", value: 3},
  riptide: {req: "operationsCleared", value: 1},
  quietstep: {req: "operationsCleared", value: 2},
  firebrand: {req: "gauntletClears", value: 1},
};
