// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// What each unlockable team lead is gated behind.

export const LEADGATES = {
  coldwire: {req: "store", price: 300},
  firebrand: {req: "store", price: 380},
  loneedge: {req: "store", price: 420},
  skunkworks: {req: "store", price: 420},
  quietstep: {req: "store", price: 450},
  quartermaster: {req: "store", price: 480},
  coronet: {req: "store", price: 520},
  riptide: {req: "store", price: 520},
  salvagerights: {req: "store", price: 500},
  fieldrefit: {req: "store", price: 500},
};
