// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// What each unlockable team lead is gated behind.

export const LEADGATES = {
  riptide: {req: "store", price: 380},
  loneedge: {req: "store", price: 420},
  skunkworks: {req: "store", price: 420},
  quietstep: {req: "store", price: 450},
  firebrand: {req: "store", price: 480},
};
