// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// The 3 team leads and their perks.

export const LEADS = {
  ironbrand: {
    n: "VALE",
    call: "IRONBRAND",
    role: "Line Commander",
    col: "#4de8ff",
    bio: "Held the Sundering Gate for nine days with a company of forty. Believes armour is a philosophy.",
    passive: {n: "Hardened Frames", d: "Every unit you deploy arrives with +1 hull."},
  },
  wildfire: {
    n: "KESTREL",
    call: "WILDFIRE",
    role: "Strike Officer",
    col: "#ff4d8f",
    bio: "Three commendations, two demotions, one very expensive orbital incident. Fights fast and asks after.",
    active: {n: "Emergency Requisition", d: "Once per mission: +4 deploy points immediately."},
  },
  coldwire: {
    n: "SABLE",
    call: "COLDWIRE",
    role: "Field Engineer",
    col: "#ffc94d",
    bio: "Speaks to machines more than people. The machines, notably, keep working.",
    passive: {n: "Nanite Weave", d: "All your units repair 1 hull at the end of every turn."},
  },
};
