// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// Mission types and battlefield modifiers.

export const MISSIONS = {
  stronghold: {
    n: "Defend Stronghold",
    waves: 8,
    d: "Hold the line through every wave. Each lane's grid charge absorbs one breach — after that, one body through ends it.",
  },
  civilians: {
    n: "Protect Civilians",
    waves: 7,
    d: "Three civilian pods sit on your ground. Lose all three and the operation fails.",
  },
  specimens: {
    n: "Acquire Specimens",
    waves: 7,
    d: "Destroy the marked hostile type to fill the quota.",
  },
  crystals: {
    n: "Fight for Crystals",
    waves: 6,
    d: "Four crystal nodes on the field. Hold three when the last wave clears.",
  },
  retake: {
    n: "Retake Ground",
    waves: 7,
    d: "Hold 3 or more tiles in the hostile half when the last wave clears. Bring something that deploys behind their line.",
  },
  extract: {n: "Extraction", waves: 6, d: "Short and heavy. Survive to extraction."},
  uplink: {
    n: "Establish Uplink",
    waves: 7,
    d: "A relay tile sits in contested ground. Hold it three turns in a row to bring the uplink online.",
  },
  blitz: {
    n: "Eradication Blitz",
    waves: 6,
    d: "Purge the zone. Destroy ten hostiles before the wave count runs out.",
  },
};
