// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// Battlefield modifiers rolled onto campaign nodes.

export const MODS = {
  none: {n: "—", d: ""},
  nest: {n: "Nest", d: "Emplacements from wave one."},
  blackout: {n: "Blackout", d: "No wave preview and no spawn markers."},
  breach: {n: "Hull breach", d: "The top lane is impassable."},
  scavenge: {n: "Scavenge", d: "Each kill refunds 1 deploy point."},
  swarm: {n: "Swarm", d: "Crawler counts doubled."},
  crumble: {
    n: "Crumbling Ground",
    d: "Every couple of turns, one open tile collapses for good — impassable to both sides.",
  },
  fog: {
    n: "Fog of War",
    d: "The middle and far ground are hidden. Most units see two cells around them; scouts see three; a Recon Lark lifts the fog for a turn.",
  },
};
