// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// Stratagem calls: one per mission, seeded by the team lead.

export const STRATAGEMS = {
  duel: {
    n: "Duel Protocol",
    dp: 3,
    target: "friendly",
    d: "One unit gains +4 damage and takes no damage until your next turn.",
  },
  refit: {
    n: "Field Refit",
    dp: 2,
    target: "none",
    d: "Every Tech unit you control is restored to full hull.",
  },
  insertion: {
    n: "Silent Insertion",
    dp: 2,
    target: "none",
    d: "The next three units you deploy this turn may land on any tile, held or not.",
  },
  breach: {
    n: "Breaching Charge",
    dp: 3,
    target: "column",
    d: "Destroy every hostile in the chosen column that is at or below 8 hull. Lands at the end of the turn you call it, once the horde has moved.",
    now: 1,
  },
  grapple: {
    n: "Grapple Net",
    dp: 2,
    target: "lane",
    d: "Drag every hostile in the chosen lane two cells back toward their edge.",
  },
  requisition: {
    n: "Emergency Requisition",
    dp: 0,
    target: "none",
    d: "+4 deploy points when the call lands.",
  },
};
