// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// Human-readable names for each targeting geometry.

export const TGNAME = {
  first: "First hostile in lane",
  furthest: "Furthest hostile in lane",
  lane: "Every hostile in the lane",
  ahead3: "Three cells ahead",
  blast4: "3x3 at exactly range 4",
  adj: "Adjacent cell",
  around: "All eight surrounding cells",
  adj4: "One adjacent hostile",
  archer: "Two ahead plus both rear diagonals",
  vert3: "Three cells vertically, one column ahead",
  bothsides: "The cell ahead and the cell behind",
  ahead2: "Both cells one and two ahead",
  range3: "Exactly three cells ahead",
  diag: "The four diagonals only",
  range2: "Exactly two cells ahead",
  boardFurthest: "Any hostile on the board — defaults to the deepest",
  rear: "Nearest hostile BEHIND it in the lane",
  wings: "Both forward diagonals — nothing in the centre",
  sweep: "Every cell in the two columns directly ahead",
  cross3: "A cross centred three cells ahead",
  cone: "A flame cone — one cell ahead, then three across",
  window: "Two and three cells ahead — blind to the adjacent cell",
  cross4: "A cross centred four cells ahead",
  sweep5: "The cell either side and the three ahead",
  rearvert3: "The column directly behind, across three lanes",
  radius2: "Any hostile within two cells",
};
