// GENERATED by tools/gen-content.js from reference/gridfall-data.json.
// Edit the JSON and re-run `npm run gen:content` — do not edit this file by hand.
// Board, economy and save constants.

export const LANES = 5;
export const COLS = 8;
export const MAXDP = 6;
export const MAXBREACH = 1;
export const DECKSIZE = 12;
export const SAVE_VERSION = 4;
export const STARTER = ["scout", "rifle", "marks", "wall", "medic", "turret", "lancer", "bulwark", "assassin"];
