#!/usr/bin/env node
// Regenerates src/content/*.js from reference/gridfall-data.json.
//
// The JSON is the source of truth for every number and every string in the game
// (it was extracted verbatim from the reference build). Content modules are
// generated rather than hand-maintained so a balance change is a one-line edit
// to the data file, and `npm run check:content` can prove the two never drift.
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const data = JSON.parse(readFileSync(join(root, 'reference/gridfall-data.json'), 'utf8'));

// Emit an object literal that reads like hand-written source: one entry per
// line-group, keys unquoted where they are valid identifiers.
const ident = /^[A-Za-z_$][\w$]*$/;
const lit = (v, indent = 0) => {
  const pad = ' '.repeat(indent);
  if (v === null) return 'null';
  if (Array.isArray(v)) {
    const flat = v.every(x => typeof x !== 'object' || x === null);
    if (flat) return `[${v.map(x => lit(x)).join(', ')}]`;
    return `[\n${v.map(x => pad + '  ' + lit(x, indent + 2)).join(',\n')},\n${pad}]`;
  }
  if (typeof v === 'object') {
    const entries = Object.entries(v);
    if (!entries.length) return '{}';
    const inline = entries.every(([, x]) => typeof x !== 'object' || x === null) &&
      JSON.stringify(v).length < 90;
    const body = entries.map(([k, x]) => `${ident.test(k) ? k : JSON.stringify(k)}: ${lit(x, indent + 2)}`);
    if (inline) return `{${body.join(', ')}}`;
    return `{\n${body.map(b => pad + '  ' + b).join(',\n')},\n${pad}}`;
  }
  return JSON.stringify(v);
};

const emit = (file, header, name, value) => {
  const src = `${header}\nexport const ${name} = ${lit(value)};\n`;
  writeFileSync(join(root, 'src/content', file), src);
  console.log(`  wrote src/content/${file}`);
};

const banner = t => `// GENERATED by tools/gen-content.js from reference/gridfall-data.json.\n// Edit the JSON and re-run \`npm run gen:content\` — do not edit this file by hand.\n// ${t}\n`;

emit('cards.js', banner('The 39 deployable cards, keyed by card id.'), 'POOL', data.cards);
emit('gear.js', banner('The 8 gear pieces, one slot per card, bought with salvage.'), 'GEAR', data.gear);
emit('hostiles.js', banner('The 11 hostile types — the bestiary.'), 'BEST', data.hostiles);
emit('leads.js', banner('The team leads and their perks.'), 'LEADS', data.leads);
emit('stratagems.js', banner('Stratagem calls: one per mission, seeded by the team lead.'), 'STRATAGEMS', data.stratagems);
emit('lead-unlocks.js', banner('What each unlockable team lead is gated behind.'), 'LEADGATES', data.leadUnlocks);
emit('missions.js', banner('Mission types and battlefield modifiers.'), 'MISSIONS', data.missions);
writeFileSync(join(root, 'src/content/modifiers.js'),
  `${banner('Battlefield modifiers rolled onto campaign nodes.')}\nexport const MODS = ${lit(data.modifiers)};\n`);
console.log('  wrote src/content/modifiers.js');
emit('operations.js', banner(`The ${Object.keys(data.operations).length} campaign operations — maps, zones, nodes and edges.`), 'OPS', data.operations);
emit('doctrines.js', banner('Enemy doctrines: how a wave distributes itself across lanes.'), 'DOCTRINE', data.doctrines);
emit('targeting-names.js', banner('Human-readable names for each targeting geometry.'), 'TGNAME', data.targeting);

const c = data.constants;
writeFileSync(join(root, 'src/state/constants.js'), `${banner('Board, economy and save constants.')}
export const LANES = ${c.LANES};
export const COLS = ${c.COLS};
export const MAXDP = ${c.MAXDP};
export const MAXBREACH = ${c.MAXBREACH};
export const DECKSIZE = ${c.DECKSIZE};
export const SAVE_VERSION = ${c.SAVE_VERSION};
export const STARTER = ${lit(c.STARTER)};
`);
console.log('  wrote src/state/constants.js');
console.log('content regenerated.');
